name: wallpaper
description: A simple wallpaper app by ablinfotech.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  http: ^0.13.3
  flutter_snake_navigationbar: ^0.5.0
  flutter_signin_button: ^2.0.0
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.8
  hexcolor: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf


  # To add assets to your application, add an assets section, like this:


